# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Backward Compatibility"

on:
  pull_request:
  push:
    branches:
      - "1.8.x"

env:
  COMPOSER_ROOT_VERSION: "1.8.x-dev"

concurrency:
  group: bc-${{ github.head_ref || github.run_id }} # will be canceled on subsequent pushes in pull requests but not branches
  cancel-in-progress: true

jobs:
  backward-compatibility:
    name: "Backward Compatibility"

    runs-on: "ubuntu-latest"
    timeout-minutes: 60

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "8.0"

      - name: "Install dependencies"
        run: "composer install --no-dev --no-interaction --no-progress"

      - name: "Install BackwardCompatibilityCheck"
        run: |
          composer global config minimum-stability dev
          composer global config prefer-stable true
          composer global require --dev ondrejmirtes/backward-compatibility-check:^5.0.9

      - name: "Check"
        run: "$(composer global config bin-dir --absolute)/roave-backward-compatibility-check"
