# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Compile PHAR"

on:
  push:
    branches:
      - "master"
    tags:
      - '*'

jobs:
  compile:
    name: "Compile PHAR"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 0

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "8.0"

      - name: "Install dependencies"
        run: "composer install --no-interaction --no-progress --no-suggest"

      - name: "Install compiler dependencies"
        run: "composer install --no-interaction --no-progress --no-suggest --working-dir=compiler"

      - name: "Transform source code"
        run: php bin/transform-source.php

      - name: "Compile PHAR"
        run: php compiler/bin/compile

      - name: "Configure GPG signing key"
        run: echo "$GPG_SIGNING_KEY" | base64 --decode | gpg --import --no-tty --batch --yes
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}

      - name: "Get Git log"
        id: git-log
        run: echo ::set-output name=log::$(git log ${{ github.event.before }}..${{ github.event.after }} --reverse --pretty='%H %s' | sed -e 's/^/https:\/\/github.com\/phpstan\/phpstan-src\/commit\//')

      - name: "Checkout phpstan-dist"
        uses: "actions/checkout@v2"
        with:
          repository: phpstan/phpstan
          path: phpstan-dist
          token: ${{ secrets.PAT }}

      - name: "cp PHAR"
        run: cp tmp/phpstan.phar phpstan-dist/phpstan.phar

      - name: "Sign PHAR"
        working-directory: phpstan-dist
        run: rm phpstan.phar.asc && gpg --command-fd 0 --pinentry-mode loopback -u "$GPG_ID" --batch --detach-sign --armor --output phpstan.phar.asc phpstan.phar
        env:
          GPG_ID: ${{ secrets.GPG_ID }}

      - name: "Verify PHAR"
        working-directory: phpstan-dist
        run: "gpg --verify phpstan.phar.asc"

      - name: "Set Git signing key"
        working-directory: phpstan-dist
        run: git config user.signingkey "$GPG_ID"
        env:
          GPG_ID: ${{ secrets.GPG_ID }}

      - name: "Configure Git"
        working-directory: phpstan-dist
        run: |
          git config user.email "ondrej@mirtes.cz" && \
          git config user.name "Ondrej Mirtes"

      - name: "Commit PHAR - master"
        working-directory: phpstan-dist
        if: "!startsWith(github.ref, 'refs/tags/')"
        run: |
          git add phpstan.phar phpstan.phar.asc && \
          git commit -S -m "Updated PHPStan to commit ${{ github.event.after }}" -m "${{ steps.git-log.outputs.log }}" && \
          git push --quiet origin master

      - name: "Commit PHAR - tag"
        working-directory: phpstan-dist
        if: "startsWith(github.ref, 'refs/tags/')"
        run: |
          git add phpstan.phar phpstan.phar.asc && \
          git commit -S -m "PHPStan ${GITHUB_REF#refs/tags/}" -m "${{ steps.git-log.outputs.log }}" && \
          git push --quiet origin master && \
          git tag -s ${GITHUB_REF#refs/tags/} -m "${GITHUB_REF#refs/tags/}" && \
          git push --quiet origin ${GITHUB_REF#refs/tags/}
