# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Base PR on previous branch"

on:
  pull_request_target:
    types:
      - opened
    branches:
      - '1.12.x'


jobs:
  comment:
    name: "Comment on pull request"
    runs-on: 'ubuntu-latest'

    steps:
      - name: Comment PR
        uses: peter-evans/create-or-update-comment@v4
        with:
          body: "You've opened the pull request against the latest branch 1.12.x. If your code is relevant on 1.11.x and you want it to be released sooner, please rebase your pull request and change its target to 1.11.x."
          token: ${{ secrets.PHPSTAN_BOT_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
